"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArtworkCard } from "@/components/artwork-card";
import { SiteHeader } from "@/components/site-header";
import { languageFrom, localize, withLanguage } from "@/lib/i18n";
import type { PublicPainting } from "@/lib/static-data";
import type { StaticSiteSummary } from "@/lib/static-types";

export function StaticHomeView({ paintings, summary }: { paintings: PublicPainting[]; summary: StaticSiteSummary }) {
  const searchParams = useSearchParams(); const lang = languageFrom({ lang: searchParams.get("lang") ?? undefined }); const zh = lang === "zh";
  return <><SiteHeader /><main className="mx-auto w-full max-w-7xl px-5 py-10 sm:px-8 sm:py-14"><section className="hero-wash relative overflow-hidden rounded-[var(--radius-hero)] px-7 py-14 sm:px-12 sm:py-20"><p className="eyebrow">DIGITAL HUMANITIES · {zh ? "中法双语" : "BILINGUE CHINOIS–FRANÇAIS"}</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight text-[var(--text-primary)] sm:text-6xl">{zh ? <>印象派女性题材<br />视觉数据库</> : <>Femmes dans<br />l&apos;impressionnisme</>}</h1><p className="mt-4 text-lg italic text-[var(--text-secondary)]">{zh ? "Femmes dans l’impressionnisme" : "Base visuelle des femmes dans l’impressionnisme"}</p><p className="mt-7 max-w-2xl leading-8 text-[var(--text-secondary)]">{localize(lang, "空间 · 身份 · 女性形象。以真实作品资料为起点，呈现印象派绘画中女性的社会位置、日常场景与视觉叙事。", "Espace · identité · figures féminines. À partir d’œuvres documentées, la base explore les positions sociales, les scènes quotidiennes et les récits visuels des femmes dans l’impressionnisme.")}</p><Link href={withLanguage("/collection", lang)} className="button-primary mt-8">{localize(lang, "探索作品", "Explorer la collection")}</Link></section><section className="mt-8 grid gap-4 sm:grid-cols-2"><Link href={withLanguage("/collection?scope=PUBLIC", lang)} className="space-entry space-public"><span>{localize(lang, "公共空间", "Espace public")}</span><strong>{zh ? "Espace public" : "Public"}</strong><small>{localize(lang, "剧院、街道、公园、咖啡馆与城市生活", "Théâtres, rues, jardins, cafés et vie urbaine")}</small></Link><Link href={withLanguage("/collection?scope=PRIVATE", lang)} className="space-entry space-private"><span>{localize(lang, "私人空间", "Espace privé")}</span><strong>{zh ? "Espace privé" : "Privé"}</strong><small>{localize(lang, "家庭、室内、阳台与亲密的日常时刻", "Intérieurs, balcons, foyers et moments d’intimité")}</small></Link></section><section className="stats-grid mt-8"><div><strong>{summary.paintingCount}</strong><span>{localize(lang, "件正式作品", "œuvres")}</span></div><div><strong>{summary.artistCount}</strong><span>{localize(lang, "位艺术家", "artistes")}</span></div><div><strong>{summary.imageCount}</strong><span>{localize(lang, "已关联图片", "images associées")}</span></div></section><section className="mt-16"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="eyebrow">{localize(lang, "数据库精选", "SÉLECTION DE LA BASE")}</p><h2 className="mt-1 text-3xl font-semibold text-[var(--text-primary)]">{localize(lang, "从作品开始阅读", "Lire à partir des œuvres")}</h2></div><Link href={withLanguage("/collection", lang)} className="text-sm text-[var(--accent)] hover:underline">{localize(lang, "查看全部作品", "Voir toutes les œuvres")}</Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{paintings.map(painting => <ArtworkCard key={painting.code} painting={painting} lang={lang} />)}</div></section></main></>;
}
